const dataResources = [
  {
    title: "Google Arts and Culture Partnerships",
    description: "Collaboration program for cultural institutions, museums, and humanities researchers to digitize, preserve, and showcase high-resolution cultural heritage collections.",
    link: "https://about.artsandculture.google.com/partners/",
    tags: ["Program", "Humanities"],
  },
  {
    title: "Sponsorship of Conferences and Events",
    description: "Sponsorship programs and guidelines supporting academic conferences, scientific workshops, and research symposia across diverse scientific disciplines.",
    link: "https://about.google/brand-resource-center/guidance/sponsorships/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Natural Questions Dataset",
    description: "Large-scale benchmark dataset of 300k+ real Google search queries paired with Wikipedia answers for training and evaluating question answering and NLP models.",
    link: "https://ai.google.com/research/NaturalQuestions",
    tags: ["Data", "Computer"],
  },
  {
    title: "ai.google",
    description: "Central portal to Google AI research, showcasing scientific breakthroughs, open-source AI technologies, Responsible AI principles, and publications.",
    link: "https://ai.google/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "AI for Social Good / AI Impact Challenge",
    description: "Grant and support initiative funding projects that apply machine learning to global challenges in climate, public health, disaster response, and socioeconomic equity.",
    link: "https://ai.google/advancing-ai/social-impact/",
    tags: ["Program", "Humanities", "Health", "Earth"],
  },
  {
    title: "Google AI Blog",
    description: "Technical research blog featuring in-depth explanations, benchmark results, and updates on Google's latest AI models, algorithms, and scientific discoveries.",
    link: "https://ai.google/latest-news/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "AlphaFold",
    description: "Groundbreaking AI system and 200M+ structure database predicting 3D protein structures with atomic accuracy for structural biology and drug discovery.",
    link: "https://alphafold.ebi.ac.uk/",
    tags: ["Tool", "Health", "Engineering"],
  },
  {
    title: "AlphaMissense",
    description: "Deep learning tool cataloging and predicting the clinical pathogenicity of all 216 million possible human missense genetic variants to aid genomics research.",
    link: "https://alphamissense.hegelab.org/",
    tags: ["Tool", "Health", "Engineering"],
  },
  {
    title: "Google Arts & Culture Platform",
    description: "Interactive platform and digital archive of high-resolution artworks, historical manuscripts, 3D artifacts, and virtual exhibits for digital humanities research.",
    link: "https://artsandculture.google.com/",
    tags: ["Data", "Humanities"],
  },
  {
    title: "Google Books",
    description: "Comprehensive digital library enabling full-text search, citation lookup, and historical corpus analysis across millions of digitized books and publications.",
    link: "https://books.google.com/",
    tags: ["Data", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Cloud Platform (GCP)",
    description: "Cloud infrastructure providing scalable compute (GPUs/TPUs), high-performance computing (HPC), distributed storage, and AI platforms for scientific research.",
    link: "https://cloud.google.com/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "BigQuery",
    description: "Serverless, petabyte-scale data warehouse with built-in SQL machine learning (BigQuery ML) and geospatial analytics for large-scale scientific data processing.",
    link: "https://cloud.google.com/bigquery",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "MedLM",
    description: "Medically-tuned foundation LLMs built on Med-PaLM 2 for clinical question answering, medical summarization, and healthcare workflow research.",
    link: "https://cloud.google.com/blog/topics/healthcare-life-sciences/introducing-medlm-for-the-healthcare-industry",
    tags: ["Tool", "Health"],
  },
  {
    title: "GCP Public Datasets",
    description: "Curated repository of public scientific datasets (genomics, satellite imagery, climate, healthcare) hosted for query in BigQuery and Cloud Storage.",
    link: "https://cloud.google.com/datasets",
    tags: ["Data", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Healthcare API",
    description: "HIPAA-compliant managed API bridging healthcare systems with cloud analytics, supporting FHIR, HL7v2, and DICOM medical imaging data.",
    link: "https://cloud.google.com/healthcare-api",
    tags: ["Tool", "Health"],
  },
  {
    title: "Google Kubernetes Engine (GKE)",
    description: "Managed Kubernetes container orchestration service for running scalable, distributed scientific computing pipelines, simulations, and GPU/TPU clusters.",
    link: "https://cloud.google.com/kubernetes-engine?hl=en",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Life Sciences API",
    description: "Cloud genomics and bioinformatics tool suite for processing secondary genomic sequencing pipelines, variant analysis, and multi-omics data.",
    link: "https://cloud.google.com/life-sciences-solutions?hl=en",
    tags: ["Tool", "Health"],
  },
  {
    title: "Compute Engine",
    description: "Scalable virtual machine infrastructure with configurable CPUs, memory, and NVIDIA GPUs for high-performance computing (HPC) and simulation workloads.",
    link: "https://cloud.google.com/products/compute",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Cloud SQL",
    description: "Fully managed relational database service (PostgreSQL with PostGIS, MySQL, SQL Server) for managing structured scientific datasets and research applications.",
    link: "https://cloud.google.com/sql",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Cloud Storage",
    description: "Scalable, high-durability object storage for storing and sharing large scientific datasets, raw sensor data, imaging archives, and ML models.",
    link: "https://cloud.google.com/storage",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Vertex AI",
    description: "Unified enterprise AI platform for training, fine-tuning, evaluating, and deploying custom ML models and foundation LLMs (Gemini, open models) on GCP.",
    link: "https://cloud.google.com/vertex-ai",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "CodeLabs",
    description: "Guided, hands-on coding tutorials and interactive walk-throughs covering machine learning, cloud architecture, geospatial analysis, and developer APIs.",
    link: "https://codelabs.developers.google.com/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Colaboratory (Colab)",
    description: "Hosted Jupyter notebook environment providing free GPU and TPU access for rapid prototyping, data science, and reproducible scientific code sharing.",
    link: "https://colab.google/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Datacommons.org",
    description: "Open knowledge graph synthesizing global public data from the UN, CDC, World Bank, and NOAA into a unified queryable schema for cross-domain analysis.",
    link: "https://datacommons.org/",
    tags: ["Data", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Dataset Search",
    description: "Specialized scientific search engine indexing millions of research datasets across academic repositories, government portals, and scientific journals.",
    link: "https://datasetsearch.research.google.com/",
    tags: ["Data", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "DeepMind.google",
    description: "Hub for Google DeepMind research publications, open science breakthroughs, and technical reports across biology, materials science, and AI theory.",
    link: "https://deepmind.google/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "WeatherNext",
    description: "AI-driven numerical weather and climate prediction models (GraphCast, MetNet) delivering fast, high-resolution atmospheric forecasts and extreme weather tracking.",
    link: "https://deepmind.google/technologies/weathernext/",
    tags: ["Tool", "Earth"],
  },
  {
    title: "Google Developers",
    description: "Developer portal with comprehensive API documentation, SDKs, reference guides, and code samples for building applications on Google technologies.",
    link: "https://developers.google.com/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Developers Experts",
    description: "Global network of recognized external tech experts offering technical mentorship, workshops, and community expertise in AI, Cloud, and Web technologies.",
    link: "https://developers.google.com/community/experts",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "DevLibrary",
    description: "Curated showcase of community-built open-source projects, code architectures, and tutorials using TensorFlow, JAX, and Google Cloud.",
    link: "https://devlibrary.withgoogle.com/products/ml?sort=added",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Forms",
    description: "Web-based tool for creating research surveys, participant questionnaires, and intake forms with automatic Google Sheets data export.",
    link: "https://docs.google.com/forms/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "JAX",
    description: "High-performance Python library for numerical computing and machine learning research, featuring automatic differentiation and XLA compilation on GPUs/TPUs.",
    link: "https://docs.jax.dev/en/latest/",
    tags: ["Tool", "Computer", "Engineering"],
  },
  {
    title: "Google Drive",
    description: "Secure cloud storage and collaboration platform for organizing, syncing, and sharing research documents, raw data, and scientific assets.",
    link: "https://drive.google.com/corp/drive/my-drive",
    tags: ["Data", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Earth Engine",
    description: "Planetary-scale geospatial analysis platform combining multi-petabyte satellite imagery (Sentinel, Landsat) with cloud compute APIs for Earth observation.",
    link: "https://earthengine.google.com/",
    tags: ["Tool", "Earth"],
  },
  {
    title: "Google Earth Engine for Research",
    description: "Noncommercial access program offering free geospatial compute quota and planetary satellite datasets for academic research and environmental nonprofits.",
    link: "https://earthengine.google.com/noncommercial/",
    tags: ["Program", "Earth"],
  },
  {
    title: "Collaborations with Universities and Higher Ed",
    description: "Institutional partnership initiatives providing higher education technology solutions, collaborative research tools, and academic infrastructure.",
    link: "https://edu.google.com/intl/ALL_au/resources/institution-type/higher-ed-solutions/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Cloud Research Credits Program",
    description: "Grant program awarding free Google Cloud compute credits to academic researchers and PhD students for compute- and data-intensive research projects.",
    link: "https://edu.google.com/programs/credits/research/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Fitbit (for Research)",
    description: "Wearable biometric sensors and research data platform capturing continuous physiological metrics (HRV, sleep, activity, SpO2) for clinical and cohort studies.",
    link: "https://enterprise.fitbit.com/researchers/",
    tags: ["Tool", "Health", "Humanities"],
  },
  {
    title: "Flax",
    description: "Flexible, high-performance neural network library for JAX designed for cutting-edge deep learning, LLM training, and scientific machine learning.",
    link: "https://flax.readthedocs.io/en/latest/",
    tags: ["Tool", "Computer", "Engineering"],
  },
  {
    title: "DeepMind's Open Source",
    description: "Official GitHub repositories hosting open-source research code, model architectures, and libraries (AlphaFold, Haiku, Optax) from Google DeepMind.",
    link: "https://github.com/google-deepmind",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Research Open Source",
    description: "Open-source repository hosting reproducible scientific algorithms, model implementations, and benchmarks accompanying Google Research publications.",
    link: "https://github.com/google-research",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Population Dynamics Foundation Model",
    description: "Open-source ML model for analyzing and forecasting spatiotemporal human population dynamics, demographic shifts, and mobility patterns.",
    link: "https://github.com/google-research/population-dynamics",
    tags: ["Tool", "Earth", "Humanities"],
  },
  {
    title: "Model Search",
    description: "Open-source AutoML framework for automatically searching, designing, and optimizing deep neural network architectures for custom datasets.",
    link: "https://github.com/google/model_search",
    tags: ["Tool", "Computer"],
  },
  {
    title: "Google Groups",
    description: "Discussion forum and mailing list platform for coordinating academic working groups, research consortiums, and open-source project communications.",
    link: "https://groups.google.com/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "COVID-19 Open Data",
    description: "Global public epidemiological dataset integrating case metrics, hospitalizations, vaccinations, search symptom trends, and mobility data for disease modeling.",
    link: "https://health.google.com/covid-19/open-data/",
    tags: ["Data", "Health"],
  },
  {
    title: "Google Health Studies App",
    description: "Mobile clinical research platform enabling researchers to recruit participants and conduct decentralized digital health and epidemiology studies on Android.",
    link: "https://health.google/consumers/health-studies/",
    tags: ["Tool", "Data", "Health"],
  },
  {
    title: "health.google",
    description: "Research portal showcasing Google Health's clinical studies, AI diagnostics in medical imaging (radiology, dermatology, ophthalmology), and digital health innovations.",
    link: "https://health.google/health-research/",
    tags: ["Program", "Knowledge", "Health"],
  },
  {
    title: "Environmental Insights Explorer",
    description: "Data analytics platform providing actionable city-scale estimates of building emissions, transport carbon footprints, tree canopy cover, and rooftop solar potential.",
    link: "https://insights.sustainability.google/",
    tags: ["Tool", "Earth", "Humanities"],
  },
  {
    title: "Keras",
    description: "High-level deep learning framework supporting JAX, TensorFlow, and PyTorch backends for fast prototyping and training of complex neural network architectures.",
    link: "https://keras.io/",
    tags: ["Tool", "Computer", "Engineering"],
  },
  {
    title: "Looker Studio (formerly Google Data Studio)",
    description: "Interactive data visualization tool for building dynamic, shareable scientific dashboards and reports connected directly to BigQuery and SQL databases.",
    link: "https://lookerstudio.google.com/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "MediaPipe",
    description: "Cross-platform framework for real-time multimodal ML pipelines (pose estimation, facial landmark tracking, hand tracking, object detection) on web and mobile.",
    link: "https://mediapipe-studio.webapps.google.com/home",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "NotebookLM",
    description: "Personalized AI research assistant grounded strictly in your uploaded papers and documents for source-cited literature synthesis, summarization, and brainstorming.",
    link: "https://notebooklm.google/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Open Source",
    description: "Portal for Google's open-source programs, grants, and community initiatives supporting open software development and scientific code transparency.",
    link: "https://opensource.google/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Cloud Partner",
    description: "Directory of certified technology partners and integrators assisting institutions in architecting and deploying Google Cloud HPC and data solutions.",
    link: "https://partners.cloud.google.com/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Patents",
    description: "Global search engine indexing 120M+ patent publications worldwide for prior art search, patent classification (CPC/IPC), and IP landscape analysis.",
    link: "https://patents.google.com/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Public Sector",
    description: "FedRAMP-compliant cloud, AI, and HPC infrastructure tailored for government research laboratories, national agencies, and defense science initiatives.",
    link: "https://publicsector.google/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "AudioSet",
    description: "Large-scale audio dataset of 2M+ human-labeled sound clips structured in a 632-class ontology for bioacoustics and machine listening research.",
    link: "https://research.google.com/audioset/",
    tags: ["Data", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "research.google",
    description: "Main portal indexing thousands of peer-reviewed publications, open-source projects, and ongoing research initiatives from Google Research.",
    link: "https://research.google/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Ionosphere",
    description: "Crowdsourced geophysics project utilizing GNSS signals from millions of Android phones to map ionospheric electron density and space weather phenomena.",
    link: "https://research.google/blog/mapping-the-ionosphere-with-the-power-of-android/",
    tags: ["Tool", "Earth", "Engineering"],
  },
  {
    title: "Joint Research Centers",
    description: "Collaborative research centers and strategic institutional partnerships co-founded with universities to address fundamental challenges in AI and computing.",
    link: "https://research.google/programs-and-events/featured-research-collaborations/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Academic Research Awards",
    description: "Unrestricted funding program supporting world-class academic research proposals across computer science, AI, systems, and interdisciplinary sciences.",
    link: "https://research.google/programs-and-events/google-academic-research-awards/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google PhD Fellowship Program",
    description: "Prestigious fellowship providing tuition funding, living stipends, and research mentorship to outstanding doctoral students in computational sciences.",
    link: "https://research.google/programs-and-events/phd-fellowship/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Research Scholar Program",
    description: "Unrestricted financial grants (up to $60k) supporting early-career, tenure-track university professors conducting novel computational research.",
    link: "https://research.google/programs-and-events/research-scholar-program/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Research Internships",
    description: "Paid research internship opportunities for undergraduate, graduate, and PhD students to collaborate with scientists on publishable research.",
    link: "https://research.google/programs-and-events/student-engagement/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Scholar",
    description: "Academic search engine indexing scholarly literature, peer-reviewed papers, preprints, and theses, with citation tracking and researcher profile hosting.",
    link: "https://scholar.google.com.au/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Sites",
    description: "No-code website creation tool for publishing research lab homepages, grant dissemination portals, academic conference sites, and lab documentation.",
    link: "https://sites.google.com/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "TPU Research Cloud (TRC) Program",
    description: "Program granting academic researchers free access to Cloud TPU accelerator clusters to train, evaluate, and share open machine learning models.",
    link: "https://sites.research.google/trc/about/",
    tags: ["Program", "Computer", "Engineering", "Health", "Earth"],
  },
  {
    title: "Open Images Dataset",
    description: "Computer vision dataset of 9M images annotated with 16M bounding boxes, instance segmentations, and visual relationships across 600 classes.",
    link: "https://storage.googleapis.com/openimages/web/index.html",
    tags: ["Data", "Computer"],
  },
  {
    title: "Google Summer of Code",
    description: "Global mentorship program providing stipends to contributors working on open-source scientific software and computational research tools.",
    link: "https://summerofcode.withgoogle.com/",
    tags: ["Program", "Computer"],
  },
  {
    title: "Climate Change and Sustainability Research Initiatives",
    description: "Initiatives, datasets, and partnerships leveraging AI and cloud technologies for carbon-free energy, climate resilience, and environmental sustainability.",
    link: "https://sustainability.google/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Research Engagement Transparency",
    description: "Transparency center detailing Google's academic engagement principles, data access frameworks for researchers, and platform study guidelines.",
    link: "https://transparency.google/intl/en_us/researcher-engagement/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Verily",
    description: "Precision health platform developing digital clinical trial tools (Project Baseline), health data platforms, and wearable biomarkers for clinical research.",
    link: "https://verily.com/",
    tags: ["Program", "Health", "Tool"],
  },
  {
    title: "Google Workspace (formerly G Suite)",
    description: "Integrated cloud productivity suite (Docs, Sheets, Slides, Drive, Meet) enabling real-time collaboration on manuscripts, data, and presentations.",
    link: "https://workspace.google.com/intl/en_au/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Android",
    description: "Open mobile operating system and sensor platform for deploying mobile health (mHealth) studies, citizen science apps, and in-situ field research.",
    link: "https://www.android.com/everyone/research/",
    tags: ["Tool", "Computer", "Health", "Earth"],
  },
  {
    title: "CloudSkillsBoost",
    description: "Interactive training platform offering self-paced hands-on labs and learning paths for Google Cloud computing, BigQuery analytics, and machine learning.",
    link: "https://www.cloudskillsboost.google/",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Alerts",
    description: "Automated email notification service tracking new web pages, news, and academic mentions for customized scientific keywords and research topics.",
    link: "https://www.google.com.au/alerts",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Search",
    description: "Web search engine with advanced search operators for locating scientific literature, whitepapers, datasets, and grounding AI models with web context.",
    link: "https://www.google.com/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Alerts",
    description: "Custom alert monitoring service delivering periodic email digests of newly indexed articles, papers, and mentions for specified research terms.",
    link: "https://www.google.com/alerts",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Ad Grants",
    description: "In-kind advertising grants ($10k/month) for non-profits and academic outreach organizations to recruit research participants and disseminate public findings.",
    link: "https://www.google.com/grants/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google.org Impact Challenge",
    description: "Philanthropic grant program providing funding and Google technical mentorship to non-profits and universities applying tech to pressing societal challenges.",
    link: "https://www.google.com/opportunities/",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Kaggle",
    description: "Data science platform providing hosted GPU/TPU notebooks, machine learning competitions, open-source code kernels, and a collaborative research community.",
    link: "https://www.kaggle.com/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Kaggle Datasets",
    description: "Open data repository hosting 200k+ public datasets across biology, computer vision, NLP, and climate, with built-in online analysis notebooks.",
    link: "https://www.kaggle.com/datasets",
    tags: ["Data", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Industry Consortia and Alliances",
    description: "Government and industry joint research partnerships co-funded by Google to accelerate climate resilience, clean energy, and regional scientific initiatives.",
    link: "https://www.minister.industry.gov.au/ministers/husic/media-releases/teaming-google-tackle-climate-change-indo-pacific-region",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "TensorFlow",
    description: "End-to-end open-source machine learning framework for training and deploying deep learning models across distributed clusters, mobile, and web.",
    link: "https://www.tensorflow.org/",
    tags: ["Tool", "Computer", "Engineering"],
  },
  {
    title: "TensorFlow Datasets",
    description: "Curated collection of ready-to-use benchmark datasets with high-performance data loaders (tf.data) for machine learning and scientific modeling.",
    link: "https://www.tensorflow.org/datasets",
    tags: ["Data", "Computer"],
  },
  {
    title: "TensorFlow Hub",
    description: "Repository of pre-trained machine learning models and feature embeddings (vision, text, audio) for transfer learning and rapid fine-tuning.",
    link: "https://www.tensorflow.org/hub",
    tags: ["Data", "Computer", "Tool"],
  },
  {
    title: "YouTube",
    description: "Video streaming platform hosting academic conference talks, DeepMind/Google Research lectures, technical tutorials, and scientific presentations.",
    link: "https://www.youtube.com/channel/UCtFRv9O2AHqOZjjynzrv-xg",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Health AI for Developer Foundations",
    description: "Collection of open-weight models (CXR Foundation, Derm Foundation) and resources to build AI applications for medical imaging and clinical text.",
    link: "https://developers.google.com/health-ai-developer-foundations",
    tags: ["Tool", "Health"],
  },
  {
    title: "AI literacy tools",
    description: "Educational curricula and interactive training resources designed to build foundational AI skills, ML ethics understanding, and digital literacy.",
    link: "https://ai.google/literacy",
    tags: ["Knowledge", "Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Aeneas AI model",
    description: "Generative AI model designed to assist historians and epigraphists in restoring damaged ancient texts, predicting missing inscriptions, and establishing provenance.",
    link: "https://predictingthepast.com/",
    tags: ["Tool", "Humanities"],
  },
  {
    title: "AlphaGenome",
    description: "Multimodal genomic deep learning platform for predicting gene regulation, chromatin interactions, and the functional impact of non-coding genetic variants.",
    link: "https://www.alphagenomedocs.com/",
    tags: ["Tool", "Health"],
  },
  {
    title: "AlphaEarth",
    description: "Global 10-meter resolution annual satellite embedding dataset in Earth Engine for land cover classification, forest monitoring, and geospatial AI.",
    link: "https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_SATELLITE_EMBEDDING_V1_ANNUAL#description",
    tags: ["Data", "Earth"],
  },
  {
    title: "Agricultural Understanding platform",
    description: "AI and satellite platform mapping farm field boundaries, crop health, and vegetation indices at individual field levels for agriscience and food security.",
    link: "https://agri.withgoogle.com/",
    tags: ["Data", "Earth", "Tool"],
  },
  {
    title: "AI Co-scientist",
    description: "Multi-agent scientific reasoning system built on Gemini 2.0 designed to help researchers formulate novel testable hypotheses and design experimental plans.",
    link: "https://research.google/blog/accelerating-scientific-breakthroughs-with-an-ai-co-scientist/",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Quantum AI & Willow Chip",
    description: "Quantum computing hardware platform (Willow chip) and open-source Cirq framework for simulating quantum chemistry, materials science, and physics algorithms.",
    link: "https://quantumai.google/",
    tags: ["Tool", "Health", "Computer", "Engineering"],
  },
  {
    title: "MedGemma",
    description: "Open-weight multimodal medical AI models fine-tuned on clinical dialogue and biomedical imaging (X-rays, histology) for healthcare research.",
    link: "https://developers.google.com/health-ai-developer-foundations/medgemma",
    tags: ["Tool", "Health"],
  },
  {
    title: "Medical Records APIs (Health Connect)",
    description: "On-device Android API providing secure, user-consented aggregation and standardized FHIR exchange of wearable, biometric, and medical record data.",
    link: "https://health.google/health-connect-android/",
    tags: ["Data", "Health", "Computer"],
  },
  {
    title: "Education Credits",
    description: "Grant program awarding free Google Cloud credits to university faculty and instructors for classroom teaching and student lab coursework.",
    link: "https://docs.cloud.google.com/billing/docs/how-to/edu-grants",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Agent Science Skills",
    description: "Open-source collection of modular scientific tools and skills enabling AI agents to query academic APIs, perform calculations, and analyze research data.",
    link: "https://github.com/google-deepmind/science-skills",
    tags: ["Tool", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Get certified with GEAR",
    description: "Program providing free Google Cloud certification vouchers, instructor-led training, and curriculum resources for higher-education faculty and students.",
    link: "https://developers.google.com/program/gear/getcertified",
    tags: ["Program", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "Google Cloud Advanced Computing Community",
    description: "Collaborative community forum and technical knowledge hub for researchers leveraging Google Cloud for HPC, supercomputing, and quantum simulations.",
    link: "https://sites.google.com/corp/view/advancedcomputingcommunity",
    tags: ["Knowledge", "Health", "Earth", "Engineering", "Humanities", "Computer"],
  },
  {
    title: "AlphaFold Server (AlphaFold 3)",
    description: "Free web platform powered by AlphaFold 3 for predicting 3D structures and interactions of proteins, DNA, RNA, ligands, ions, and chemical modifications with atomic precision.",
    link: "https://alphafoldserver.com/",
    tags: ["Tool", "Health", "Engineering"],
  },
  {
    title: "GNoME (Materials Discovery)",
    description: "AI system and open materials dataset predicting 2.2 million new crystal structures and 380,000 stable materials to accelerate renewable energy, batteries, and superconductor research.",
    link: "https://github.com/google-deepmind/materials_discovery",
    tags: ["Data", "Tool", "Engineering"],
  },
  {
    title: "GraphCast",
    description: "State-of-the-art machine learning weather forecasting model predicting 10-day global atmospheric variables at 0.25\u00b0 resolution in under a minute on Google Cloud TPUs.",
    link: "https://github.com/google-deepmind/graphcast",
    tags: ["Tool", "Earth"],
  },
  {
    title: "NeuralGCM",
    description: "Differentiable hybrid atmospheric general circulation model combining physics-based dynamical cores with machine learning for fast, multi-decade climate simulation and weather prediction.",
    link: "https://github.com/google-research/neuralgcm",
    tags: ["Tool", "Earth"],
  },
  {
    title: "Google AI Studio",
    description: "Fast prototyping web IDE and API console for experimenting with Gemini multimodal foundation models featuring up to 2-million-token context windows for scientific research.",
    link: "https://aistudio.google.com/",
    tags: ["Tool", "Computer", "Engineering", "Health", "Earth", "Humanities"],
  },
  {
    title: "Gemma Open Models",
    description: "Family of lightweight, state-of-the-art open-weight foundation models (Gemma 2, CodeGemma, PaliGemma) for local inference, fine-tuning, and open scientific AI research.",
    link: "https://ai.google.dev/gemma",
    tags: ["Tool", "Data", "Computer"],
  },
  {
    title: "Open Buildings Dataset",
    description: "Open-access satellite dataset mapping 1.8+ billion building footprints across Africa, Latin America, and South Asia for urban planning, demographics, and disaster response.",
    link: "https://sites.research.google/open-buildings/",
    tags: ["Data", "Earth", "Humanities"],
  },
  {
    title: "Flood Hub",
    description: "AI-driven hydrological forecasting platform delivering riverine flood predictions and inundation maps up to 7 days in advance across 80+ countries.",
    link: "https://sites.research.google/floods/",
    tags: ["Tool", "Data", "Earth"],
  },
  {
    title: "Cirq & OpenFermion",
    description: "Open-source Python frameworks from Google Quantum AI for designing, simulating, and compiling quantum circuits and translating quantum chemistry problems for NISQ hardware.",
    link: "https://quantumai.google/cirq",
    tags: ["Tool", "Computer", "Engineering"],
  },
  {
    title: "Neuroglancer & H01 Connectome",
    description: "WebGL-based 3D volumetric visualization tool and petavoxel dataset for exploring nanoscale electron microscopy reconstructions of human cortex and neural connectomes.",
    link: "https://github.com/google/neuroglancer",
    tags: ["Tool", "Data", "Health", "Computer"],
  },
  {
    title: "Dynamic World",
    description: "Near real-time 10-meter resolution global land use and land cover dataset powered by deep learning on Sentinel-2 imagery in partnership with the World Resources Institute.",
    link: "https://www.dynamicworld.app/",
    tags: ["Data", "Tool", "Earth"],
  },
  {
    title: "Google Trends",
    description: "Real-time and historical search query index tracking public interest and geographical search volumes for infodemiology, public health, economics, and social science research.",
    link: "https://trends.google.com/",
    tags: ["Data", "Tool", "Health", "Humanities", "Earth"],
  },
  {
    title: "AlphaGeometry",
    description: "Neuro-symbolic AI system combining neural language models with symbolic deduction to solve complex Olympiad-level Euclidean geometry problems with formal proofs.",
    link: "https://github.com/google-deepmind/alphageometry",
    tags: ["Tool", "Computer", "Engineering"],
  },
  {
    title: "Data Commons Python Client",
    description: "Programmatic Python API library for querying the Data Commons open knowledge graph directly into pandas DataFrames for multi-domain statistical research.",
    link: "https://docs.datacommons.org/api/python/",
    tags: ["Tool", "Data", "Humanities", "Earth", "Health", "Computer"],
  },
];
